# Generated by Django 4.1.3 on 2023-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='partidas',
            field=models.IntegerField(default=0),
        ),
    ]
