# Generated by Django 4.1.3 on 2023-04-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0004_rename_partidas_game_numeropartidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='NumeroPartidas',
        ),
    ]
