# Generated by Django 4.1.3 on 2023-04-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0006_game_numpartidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='numpartidas',
        ),
    ]
