# Generated by Django 4.1.2 on 2023-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0012_game_numeropartidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='numeroPartidas',
        ),
        migrations.AddField(
            model_name='game',
            name='numPartidas',
            field=models.IntegerField(default=0),
        ),
    ]
